{{- if .Values.mysql.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dinky.name" . }}-mysql
data:
  MYSQL_ADDR: {{ .Values.mysql.url | b64enc | quote  }}
  MYSQL_USERNAME: {{ .Values.mysql.auth.username | b64enc | quote  }}
  MYSQL_PASSWORD: {{ .Values.mysql.auth.password | b64enc | quote  }}
type: Opaque
{{- end }}