{{- if .Values.externalDatabase.enabled -}}
{{ if eq .Values.externalDatabase.type "mysql" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dinky.name" . }}-mysql
data:
  MYSQL_ADDR: {{ .Values.externalDatabase.url | b64enc | quote }}
  MYSQL_USERNAME: {{ .Values.externalDatabase.auth.username | b64enc | quote  }}
  MYSQL_PASSWORD: {{ .Values.externalDatabase.auth.password | b64enc | quote  }}
type: Opaque
{{- end }}
{{- end }}