{{- if .Values.externalDatabase.enabled -}}
{{ if eq .Values.externalDatabase.type "postgresql" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dinky.name" . }}-postgres
data:
  POSTGRES_ADDR: {{ .Values.externalDatabase.url | b64enc | quote  }}
  POSTGRES_USER: {{ .Values.externalDatabase.auth.username | b64enc | quote  }}
  POSTGRES_PASSWORD: {{ .Values.externalDatabase.auth.password | b64enc | quote  }}
type: Opaque
{{- end }}
{{- end }}