{{- if .Values.postgresql.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dinky.name" . }}-postgres
data:
  POSTGRES_ADDR: {{ .Values.postgresql.url | b64enc | quote  }}
  POSTGRES_USER: {{ .Values.postgresql.auth.username | b64enc | quote  }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password | b64enc | quote  }}
type: Opaque
{{- end }}