#
#  Licensed to the Apache Software Foundation (ASF) under one or more
#  contributor license agreements.  See the NOTICE file distributed with
#  this work for additional information regarding copyright ownership.
#  The ASF licenses this file to You under the Apache License, Version 2.0
#  (the "License"); you may not use this file except in compliance with
#  the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
#

timezone: "Asia/Shanghai"

nameOverride: ""
fullnameOverride: ""

image:
  repository: "docker.dinky.org.cn:32451/dinky/dev/dinky-txh"
  pullPolicy: "Always"
  tag: "1.0.2"
  pullSecret: ""

mysql:
  enabled: false
  url: "172.168.1.111:31476"
  auth:
    username: "dinky"
    password: "bigdata123!@#"
    database: "dinky-dev-1-17"

postgresql:
  enabled: false
  url: "172.168.1.111:31476"
  auth:
    username: "dinky"
    password: "bigdata123!@#"
    database: "dinky-dev-1-17"

externalDatabase:
  enabled: true
  type: "mysql"
  url: "10.43.2.12:3306"
  auth:
    username: "root"
    password: "Dinky@1234567!"
    database: "dinky"

externalDatabaseService:
  clusterIP: 10.43.2.12
  port: 3306

externalDatabaseEndpoints:
  ip: 172.168.1.110
  port: 3306

rbac:
  create: true

spec:
  replicaCount: 1
  containerPort: 8888
  name: rest
  extraEnv:
    flinkVersion: "1.17"

  affinity: {}
  nodeSelector: {}
  tolerations: []
  resources: {}
  # resources:
  #   limits:
  #     memory: "2Gi"
  #     cpu: "1"
  #   requests:
  #     memory: "1Gi"
  #     cpu: "500m"
  livenessProbe:
    enabled: true
    initialDelaySeconds: "90"
    periodSeconds: "30"
    timeoutSeconds: "20"
    failureThreshold: "3"
    successThreshold: "1"

  readinessProbe:
    enabled: true
    initialDelaySeconds: "90"
    periodSeconds: "30"
    timeoutSeconds: "20"
    failureThreshold: "3"
    successThreshold: "1"

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: demo.dinky.org.cn
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []


service:
  ## type determines how the Service is exposed. Defaults to ClusterIP. Valid options are ExternalName, ClusterIP, NodePort, and LoadBalancer
  type: "ClusterIP"
  name: "dinky"

dinkyDefaultConfiguration:
  create: true
  append: true

dinkyServiceAccount:
  create: true
  annotations: {}
  name: "dinky"