version: "3"
networks:
  dinky_net:
    external: true
services:
  doris-fe:
    image: apache/doris:doris-fe-2.1.7
    hostname: doris-fe
    container_name: doris-fe
    environment:
      - FE_SERVERS=fe1:172.28.0.200:9010
      - FE_ID=1
    networks:
      dinky_net:
        ipv4_address: 172.28.0.200
  doris-be:
    image: apache/doris:doris-be-2.1.7
    hostname: doris-be
    container_name: doris-be
    environment:
      - FE_SERVERS=fe1:172.28.0.200:9010
      - BE_ADDR=172.28.0.201:9050
    depends_on:
      - doris-fe
    networks:
      dinky_net:
        ipv4_address: 172.28.0.201
