version: "3"
networks:
  dinky_net:
    external: true
services:
  fe:
    image: apache/doris:doris-fe-2.1.7
    hostname: fe
    container_name: fe
    environment:
      - FE_SERVERS=fe1:172.28.0.110:9010
      - FE_ID=1
    networks:
      dinky_net:
        ipv4_address: 172.28.0.110
  be:
    image: apache/doris:doris-be-2.1.7
    hostname: be
    container_name: be
    environment:
      - FE_SERVERS=fe1:172.28.0.110:9010
      - BE_ADDR=172.28.0.111:9050
#    depends_on:
#      - fe
    networks:
      dinky_net:
        ipv4_address: 172.28.0.111
