export type ClusterTableListItem = {
            id: number,
            name: string,
            alias: string,
            type: string,
            checkPoint: number,
            savePointPath: string,
            parallelism: number,
            fragment: boolean,
            clusterId: number,
            note: string,
            enabled: boolean,
            createTime: Date,
            updateTime: Date,
};
