package com.zdpx.coder.json;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.equalTo;

import org.junit.jupiter.api.Test;

import com.zdpx.coder.SceneCodeBuilder;
import com.zdpx.coder.graph.Scene;
import com.zdpx.coder.json.x6.X6ToInternalConvert;

class X6ToInternalConvertTest {

    private final String x6_json =
            "\n"
                    + "{\n"
                    + "  \"cells\": [\n"
                    + "    {\n"
                    + "      \"position\": { \"x\": 40, \"y\": 40 },\n"
                    + "      \"size\": { \"width\": 360, \"height\": 160 },\n"
                    + "      \"attrs\": { \"text\": { \"text\": \"Parent\\n(try to move me)\" } },\n"
                    + "      \"visible\": true,\n"
                    + "      \"shape\": \"package\",\n"
                    + "      \"id\": \"da936e39-1c1f-4360-835d-ac1b76bf92a4\",\n"
                    + "      \"zIndex\": 1,\n"
                    + "      \"children\": [\n"
                    + "        \"d582a458-ecb5-4099-848c-b806945860f5\",\n"
                    + "        \"dfba19c2-3b46-4255-b524-93e26de9739d\",\n"
                    + "        \"72359a19-9226-42b2-9c71-7809d090bf84\"\n"
                    + "      ]\n"
                    + "    },\n"
                    + "    {\n"
                    + "      \"position\": { \"x\": 60, \"y\": 100 },\n"
                    + "      \"size\": { \"width\": 100, \"height\": 40 },\n"
                    + "      \"attrs\": { \"text\": { \"text\": \"Child\\n(inner)\" } },\n"
                    + "      \"visible\": true,\n"
                    + "      \"shape\": \"MysqlSourceOperator\",\n"
                    + "      \"id\": \"d582a458-ecb5-4099-848c-b806945860f5\",\n"
                    + "      \"zIndex\": 2,\n"
                    + "      \"parent\": \"da936e39-1c1f-4360-835d-ac1b76bf92a4\",\n"
                    + "      \"data\": {\n"
                    + "        \"parameters\": [\n"
                    + "          {\n"
                    + "            \"tableName\": \"source\",\n"
                    + "            \"connector\": \"jdbc\",\n"
                    + "            \"url\": \"jdbc:mysql://192.168.1.88:3306/flink?allowPublicKeyRetrieval=true\",\n"
                    + "            \"username\": \"root\",\n"
                    + "            \"password\": \"123456\",\n"
                    + "            \"columns\": [\n"
                    + "              {\n"
                    + "                \"name\": \"id\",\n"
                    + "                \"type\": \"STRING\"\n"
                    + "              },\n"
                    + "              {\n"
                    + "                \"name\": \"taskId\",\n"
                    + "                \"type\": \"STRING\"\n"
                    + "              },\n"
                    + "              {\n"
                    + "                \"name\": \"longitude\",\n"
                    + "                \"type\": \"DOUBLE\"\n"
                    + "              },\n"
                    + "              {\n"
                    + "                \"name\": \"latitude\",\n"
                    + "                \"type\": \"DOUBLE\"\n"
                    + "              },\n"
                    + "              {\n"
                    + "                \"name\": \"va\",\n"
                    + "                \"type\": \"DOUBLE\"\n"
                    + "              },\n"
                    + "              {\n"
                    + "                \"name\": \"gbu_time\",\n"
                    + "                \"type\": \"TIMESTAMP\"\n"
                    + "              },\n"
                    + "              {\n"
                    + "                \"name\": \"taskStatus\",\n"
                    + "                \"type\": \"INT\"\n"
                    + "              },\n"
                    + "              {\n"
                    + "                \"name\": \"task_time\",\n"
                    + "                \"type\": \"TIMESTAMP\"\n"
                    + "              }\n"
                    + "            ]\n"
                    + "          }\n"
                    + "        ]\n"
                    + "      }\n"
                    + "    },\n"
                    + "    {\n"
                    + "      \"position\": { \"x\": 420, \"y\": 80 },\n"
                    + "      \"size\": { \"width\": 100, \"height\": 40 },\n"
                    + "      \"attrs\": { \"text\": { \"text\": \"Child\\n(outer)\" } },\n"
                    + "      \"visible\": true,\n"
                    + "      \"shape\": \"MysqlSinkOperator\",\n"
                    + "      \"id\": \"dfba19c2-3b46-4255-b524-93e26de9739d\",\n"
                    + "      \"zIndex\": 2,\n"
                    + "      \"parent\": \"da936e39-1c1f-4360-835d-ac1b76bf92a4\",\n"
                    + "      \"data\": {\n"
                    + "        \"parameters\": [\n"
                    + "          {\n"
                    + "            \"tableName\": \"sink\",\n"
                    + "            \"connector\": \"jdbc\",\n"
                    + "            \"url\": \"jdbc:mysql://192.168.1.88:3306/flink?allowPublicKeyRetrieval=true\",\n"
                    + "            \"username\": \"root\",\n"
                    + "            \"password\": \"123456\",\n"
                    + "            \"columns\": [\n"
                    + "              {\n"
                    + "                \"name\": \"id\",\n"
                    + "                \"type\": \"STRING\"\n"
                    + "              },\n"
                    + "              {\n"
                    + "                \"name\": \"taskId\",\n"
                    + "                \"type\": \"STRING\"\n"
                    + "              },\n"
                    + "              {\n"
                    + "                \"name\": \"longitude\",\n"
                    + "                \"type\": \"DOUBLE\"\n"
                    + "              },\n"
                    + "              {\n"
                    + "                \"name\": \"latitude\",\n"
                    + "                \"type\": \"DOUBLE\"\n"
                    + "              },\n"
                    + "              {\n"
                    + "                \"name\": \"va\",\n"
                    + "                \"type\": \"DOUBLE\"\n"
                    + "              },\n"
                    + "              {\n"
                    + "                \"name\": \"gbu_time\",\n"
                    + "                \"type\": \"TIMESTAMP\"\n"
                    + "              },\n"
                    + "              {\n"
                    + "                \"name\": \"taskStatus\",\n"
                    + "                \"type\": \"INT\"\n"
                    + "              },\n"
                    + "              {\n"
                    + "                \"name\": \"task_time\",\n"
                    + "                \"type\": \"TIMESTAMP\"\n"
                    + "              }\n"
                    + "            ]\n"
                    + "          }\n"
                    + "        ]\n"
                    + "      }\n"
                    + "    },\n"
                    + "    {\n"
                    + "      \"shape\": \"edge\",\n"
                    + "      \"attrs\": { \"line\": { \"stroke\": \"#8f8f8f\", \"strokeWidth\": 1 } },\n"
                    + "      \"id\": \"72359a19-9226-42b2-9c71-7809d090bf84\",\n"
                    + "      \"source\": { \"cell\": \"d582a458-ecb5-4099-848c-b806945860f5\" , \"port\": "
                    + "\"output_0\"},\n"
                    + "      \"target\": { \"cell\": \"dfba19c2-3b46-4255-b524-93e26de9739d\" , \"port\": "
                    + "\"input_0\"},\n"
                    + "      \"vertices\": [\n"
                    + "        { \"x\": 120, \"y\": 60 },\n"
                    + "        { \"x\": 200, \"y\": 100 }\n"
                    + "      ],\n"
                    + "      \"zIndex\": 3,\n"
                    + "      \"parent\": \"da936e39-1c1f-4360-835d-ac1b76bf92a4\"\n"
                    + "    }\n"
                    + "  ]\n"
                    + "}\n";

    @Test
    void convert() {
        final String expect =
                "\r\n"
                        + "CREATE TABLE source_b806945860f5 (id STRING, taskId STRING, longitude DOUBLE, latitude DOUBLE, va DOUBLE, gbu_time TIMESTAMP, taskStatus INT, task_time TIMESTAMP) WITH ('password' = '123456', 'connector' = 'jdbc', 'url' = 'jdbc:mysql://192.168.1.88:3306/flink?allowPublicKeyRetrieval=true', 'table-name' = 'source', 'username' = 'root');\r\n"
                        + "\r\n"
                        + "CREATE TABLE sink_93e26de9739d (id STRING, taskId STRING, longitude DOUBLE, latitude DOUBLE, va DOUBLE, gbu_time TIMESTAMP, taskStatus INT, task_time TIMESTAMP) WITH ('password' = '123456', 'connector' = 'jdbc', 'url' = 'jdbc:mysql://192.168.1.88:3306/flink?allowPublicKeyRetrieval=true', 'table-name' = 'sink', 'username' = 'root');\r\n"
                        + "\r\n"
                        + "INSERT INTO sink_93e26de9739d (id,taskId,longitude,latitude,va,gbu_time,taskStatus,task_time) SELECT id, taskId, longitude, latitude, va, gbu_time, taskStatus, task_time FROM source_b806945860f5;\r\n";

        X6ToInternalConvert x6 = new X6ToInternalConvert();
        Scene result = x6.convert(x6_json);
        result.getEnvironment().setResultType(ResultType.SQL);
        SceneCodeBuilder su = new SceneCodeBuilder(result);
        final String build = su.build();
        assertThat(build, equalTo(expect));
    }
}
