name: Issue Title Standard Check

on:
  issues:
    types: [opened, edited]

jobs:
  check-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-cool/issues-helper@v2.2.0
        id: check
        name: Check Issue Title
        with:
          actions: 'check-issue'
          issue-number: ${{ github.event.issue.number }}
          title-excludes: '[Bug],[Feature],[Doc],[Refactor],[Optimization],[Improvement]'

      - if: steps.check.outputs.check-result == 'false' && github.event.issue.state == 'open'
        uses: actions-cool/issues-helper@v2.2.0
        name: Create Comment
        with:
          actions: 'create-comment'
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hi @${{ github.event.issue.user.login }}, It is detected that the current Issue title is not standardized. Please refer to [Issue Notes](http://www.dinky.org.cn/docs/next/developer_guide/contribution/issue) to modify it.
            
            你好 @${{ github.event.issue.user.login }}, 检测到当前 Issue 标题不规范, 请参考 [Issue 须知](http://www.dinky.org.cn/docs/next/developer_guide/contribution/issue) 进行修改