name: k3s test
on:
  workflow_dispatch:
jobs:
  k3s:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Init  Docker Network
        run: |
          docker network create -d bridge --subnet 172.28.0.0/16  --gateway 172.28.0.1 dinky_net
      - name: Init k3s
        uses: nolar/setup-k3d-k3s@v1
        with:
          version: v1.31.4+k3s1
          k3d-args: -s 1 --network dinky_net --api-port 172.28.0.1:6550
      - name: Get k3s kube config
        run: k3d kubeconfig get --all  && mkdir ./kube && k3d kubeconfig get --all >  ./kube/k3s.yaml && sed -i 's/0.0.0.0/k8s/g' ./kube/k3s.yaml
      - name: get current k8s config
        run: |
          kubectl config view
      - name: Init k8s RBAC and namespace
        run: |
          kubectl create namespace dinky
          kubectl create serviceaccount dinky -n dinky
          kubectl create clusterrolebinding flink-role-binding-dinky --clusterrole=edit --serviceaccount=default:dinky
          kubectl get sa -n dinky
      - name: test host
        run: |
          curl -k https://172.28.0.1:6550
      - run: |
          NAMESPACE=dinky
          kubectl get pods -n $NAMESPACE

          # 获取每个Pod的日志
          echo "获取命名空间 $NAMESPACE 下每个Pod的日志"
          for POD in $(kubectl get pods -n $NAMESPACE -o jsonpath='{.items[*].metadata.name}'); do
          echo "Pod: $POD 的日志"
          kubectl logs -n $NAMESPACE $POD
          echo "------------------------"
          done

